name: Test nuget package

on: ["push"]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore Nuget Packages
        run: nuget restore HelloWorldNuget.sln

      - name: Build app and tests for release
        run: msbuild HelloWorldNuget.Framework.Tests\HelloWorldNuget.Framework.Tests.csproj -t:rebuild -property:Configuration=Release

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Test application
        run: dotnet test HelloWorldNuget.Framework.Tests\bin\Release\HelloWorldNuget.Framework.Tests.dll